const excuses = {
    homework: [
        "My dog ate my homework.",
        "I accidentally submitted it to NASA.",
        "It got lost in a parallel universe.",
        "The printer decided to rebel against me.",
        "Aliens abducted my assignment for research.",
        "My little brother turned it into a paper airplane.",
        "It fell into a black hole during a science experiment.",
        "I wrote it in invisible ink, and now I can’t read it.",
        "The ghost in my house misplaced it.",
        "I spilled coffee on it, and it dissolved.",
        "My pet hamster used it to line its cage.",
        "It was confiscated by secret agents.",
        "It got swept away by a freak indoor tornado.",
        "I accidentally donated it to charity.",
        "It’s currently being framed at the museum.",
        "It was stolen by an envious classmate.",
        "I set it on fire during a dramatic reenactment.",
        "It was eaten by a hungry neighbor’s goat.",
        "I accidentally emailed it to my grandma.",
        "My parrot shredded it out of jealousy.",
        "I used it as a napkin and then threw it away.",
        "It was turned into confetti for a surprise party.",
        "I gave it to a magician who made it disappear.",
        "I left it on the roof of my car and drove off.",
        "It was used as kindling for a campfire.",
        "My robot vacuum ate it.",
        "I left it in the bathroom at the mall.",
        "It was turned into origami by a friend.",
        "I accidentally shredded it with my bills.",
        "It got recycled with the newspapers.",
        "A gust of wind blew it out of my hand.",
        "I used it to swat a fly, and now it’s unreadable.",
        "It was taken as evidence in a crime scene.",
        "I dropped it in a puddle, and it disintegrated.",
        "It’s in the washing machine after being in my pocket.",
        "It was stolen by raccoons for their nest.",
        "It fell into my soup and became illegible.",
        "I used it to wrap a birthday present.",
        "It got stuck under a pile of other papers.",
        "It was used as a coaster and is now ruined.",
        "A monkey at the zoo snatched it from me.",
        "It was sacrificed to the volcano god.",
        "I left it on the bus, and now it’s gone.",
        "My neighbor’s kid drew all over it.",
        "It got folded into a paper hat and lost.",
        "It’s currently being analyzed by scientists.",
        "A wizard turned it into a frog.",
        "It was blown away in a freak gust of wind.",
        "I used it to clean up a spill.",
        "It’s part of a scavenger hunt and now missing.",
        "A dog I don’t own ate it."
    ],
    work: [
        "I was stuck in an elevator with no Wi-Fi.",
        "My alarm clock is on strike.",
        "A parade of ducks blocked my commute.",
        "I was practicing self-care by sleeping in.",
        "I got into an argument with my GPS and lost.",
        "The coffee shop ran out of coffee, and I couldn’t function.",
        "I accidentally boarded a train to another city.",
        "A marching band blocked my driveway.",
        "My car keys fell into a sewer grate.",
        "A circus elephant escaped and caused a traffic jam.",
        "My glasses were stolen by a mischievous monkey.",
        "I was trapped in my house by a swarm of bees.",
        "My bicycle was commandeered by a local hero.",
        "My laptop was stolen by a pigeon.",
        "I spilled smoothie on my work uniform.",
        "I got locked in my own garage.",
        "The elevator stopped on every floor on the way down.",
        "I had to detour due to a UFO landing.",
        "I got caught in a flash mob and couldn’t leave.",
        "My toddler locked me out of the house.",
        "I couldn’t find matching socks and panicked.",
        "The power went out while I was drying my hair.",
        "A goat ate my work badge.",
        "The office cat wouldn’t let me leave my car.",
        "My smartphone exploded, and I had no alarm.",
        "I got lost in my own neighborhood.",
        "My smartwatch decided to prank me with a wrong time.",
        "The bus driver was stuck in another dimension.",
        "I slipped on a banana peel and injured my pride.",
        "My neighbor borrowed my car without asking.",
        "I tripped over my cat and sprained my dignity.",
        "A raccoon hijacked my bike.",
        "I fell asleep in the bathtub.",
        "I accidentally super-glued my shoes to the floor.",
        "I got stuck in a never-ending meeting with myself.",
        "A friendly robot decided to reprogram my schedule.",
        "I followed the wrong GPS directions to a cornfield.",
        "A surprise snowstorm covered my car in July.",
        "A curious toddler hid my shoes in the freezer.",
        "My headphones were stuck in my hair, delaying me.",
        "A meteor struck my driveway, and I couldn’t leave.",
        "I got trapped in a TikTok rabbit hole.",
        "My toddler’s hamster escaped, causing a mini-crisis.",
        "I dropped my car keys in the toaster.",
        "My toddler used my car keys to build a fort.",
        "I got locked in my own closet.",
        "The bakery I stopped at was under siege by ducks.",
        "A game of hopscotch in the road blocked my way.",
        "A car-sharing app paired me with a prankster driver."
    ],
    social: [
        "I accidentally RSVP'd to another dimension.",
        "I was kidnapped by a book I couldn’t put down.",
        "My outfit was eaten by moths at the last minute.",
        "I couldn’t leave because my cat needed emotional support.",
        "The moon told me to stay home tonight.",
        "I was waiting for my pizza delivery guy to find Pluto.",
        "I got tangled in fairy lights and couldn’t escape.",
        "My clone decided to go instead of me.",
        "I forgot how to socialize and needed a refresher course.",
        "A butterfly convinced me to follow it instead.",
        "My favorite TV character came to life for a chat.",
        "I got trapped in a philosophical debate with my mirror.",
        "I accidentally sent my RSVP to outer space.",
        "A bird delivered an urgent letter requiring my attention.",
        "My horoscope said to avoid human interaction.",
        "I got stuck in a virtual reality simulation.",
        "A mime followed me home, and I couldn’t shake them.",
        "I spilled glitter everywhere and couldn’t leave it like that.",
        "My enchanted shoes wouldn’t let me leave the house.",
        "My neighbor needed help with their time machine.",
        "I was trying to find my social skills and got lost.",
        "My cat booked me for a staring contest.",
        "A fortune teller told me to avoid gatherings.",
        "My invisible friend threw a surprise party for me.",
        "I was stuck in a blanket fort of my own making.",
        "The wind whispered secrets that required my attention.",
        "I mistook the invite for a riddle and got stuck.",
        "I accidentally RSVP’d to the wrong century.",
        "I was ghosted by my own shadow.",
        "A parade of turtles blocked my driveway.",
        "My GPS rerouted me to an existential crisis.",
        "I got locked in an escape room with no exit.",
        "I was abducted by a book club and forced to read.",
        "The last slice of cake needed me for moral support.",
        "I got invited to a parallel universe and stayed too long.",
        "The neighborhood peacock wouldn’t let me leave.",
        "I had to decipher an ancient map to find my keys.",
        "My karaoke machine demanded a solo performance.",
        "A wizard’s duel broke out in my living room.",
        "I spilled nail polish on my only pair of shoes.",
        "I was stuck in a Wi-Fi-free zone and panicked.",
        "My houseplants staged a protest and needed my attention.",
        "I was hypnotized by a lava lamp and lost track of time.",
        "My imaginary friend threw a tantrum.",
        "A raccoon stole my party invitation.",
        "The stars told me to embrace solitude tonight.",
        "My time-travel watch glitched and sent me to 1776.",
        "I had to babysit my neighbor’s robot dog.",
        "My doppelgänger went in my place, and I stayed home."
    ],    
    mishap: [
        "I spilled coffee on the space-time continuum.",
        "A squirrel stole my car keys.",
        "I locked myself in my own bathroom.",
        "I forgot how to open doors momentarily.",
        "Gravity decided to work overtime on me.",
        "I tripped over my own shoelaces.",
        "My house keys fell into a jar of peanut butter.",
        "I got tangled in my scarf and couldn’t untangle myself.",
        "I sneezed and accidentally summoned a small tornado.",
        "My shadow escaped and caused chaos.",
        "I locked my keys inside the fridge.",
        "A bird mistook me for a statue and wouldn’t leave.",
        "My umbrella got stuck in the ceiling fan.",
        "I got trapped under a pile of clean laundry.",
        "A baby threw a tantrum and wouldn’t let me pass.",
        "I spilled soup on my only pair of pants.",
        "I got stuck in quicksand... in my driveway.",
        "A gust of wind carried my shoes away.",
        "I accidentally glued myself to my chair.",
        "I dropped my phone in the toilet and had to rescue it.",
        "A friendly robot locked me out of my own house.",
        "I got locked in my attic while looking for decorations.",
        "My pet goldfish flooded the tank and my living room.",
        "A raccoon hijacked my picnic basket and demanded a ransom.",
        "I got stuck trying to climb out my window.",
        "I accidentally set off my own house alarm.",
        "My pet turtle ran away, and I had to find it.",
        "I forgot my own name and had to meditate to remember.",
        "My socks got stolen by the dryer monster.",
        "I dropped my lunch on my lap and had to change.",
        "My shoelace broke, and I got stuck fixing it.",
        "I spilled paint on myself and couldn’t clean up in time.",
        "My pants ripped on my way out the door.",
        "I fell asleep in the shower and woke up late.",
        "I got tangled in my headphones and couldn’t escape.",
        "A magician borrowed my hat and never gave it back.",
        "I spilled glitter on the carpet and had to clean it.",
        "A mouse stole my favorite pen, and I got distracted.",
        "I got locked in my own car.",
        "My cat knocked over my coffee onto my schedule.",
        "I mistook the bathroom door for the exit and got stuck.",
        "A spider took over my living room.",
        "I got lost in my own neighborhood.",
        "My front door refused to open despite my best efforts.",
        "My tea kettle wouldn’t stop whistling.",
        "I dropped my keys in the gutter.",
        "I locked myself out of my house while chasing a bird.",
        "My vacuum went rogue and trapped me."
    ],    
    wild: [
        "I had to babysit my friend’s pet dragon.",
        "A rogue magician turned my car into a pumpkin.",
        "I was too busy saving the world from a robot uprising.",
        "A time traveler recruited me for an urgent mission.",
        "The stars aligned, and I couldn’t disrupt their plan.",
        "A talking tree gave me life advice for hours.",
        "I was chasing a unicorn across the park.",
        "A genie granted my wish to stay home forever.",
        "I found a treasure map and had to follow it.",
        "I became the ruler of a secret kingdom overnight.",
        "I accidentally opened a portal to another realm.",
        "My reflection challenged me to a staring contest.",
        "A pirate ship docked in my backyard.",
        "I was visited by an alien ambassador.",
        "A phoenix landed on my roof and wouldn’t leave.",
        "I joined a wizard’s duel and lost track of time.",
        "A meteor crashed in my garden.",
        "A band of elves needed my help crafting toys.",
        "I tamed a wild bear and named it Gary.",
        "I was swept away by a tornado to Oz.",
        "I had to negotiate peace between dragons and knights.",
        "I found Atlantis in my backyard pool.",
        "My house floated away in a hot air balloon.",
        "I got stuck in an enchanted forest.",
        "A witch turned my shoes into bricks.",
        "A talking cat sent me on a quest for milk.",
        "My magic broomstick ran out of fuel.",
        "A griffin carried away my homework.",
        "A spell gone wrong turned my room into a swamp.",
        "A vampire mistook me for a long-lost relative.",
        "I hosted a tea party for ghosts.",
        "An army of squirrels recruited me as their leader.",
        "I was frozen in time by a wizard’s curse.",
        "A giant beanstalk grew in my living room.",
        "A leprechaun tricked me into searching for gold.",
        "I adopted a baby dragon and had to find it food.",
        "A wizard’s apprentice turned me into a frog.",
        "I rode a Pegasus into the sunset.",
        "An enchanted book pulled me into its story.",
        "I had to babysit an alien child.",
        "A fairy godmother gave me chores instead of wishes.",
        "A portal to another galaxy opened in my kitchen.",
        "A kraken blocked my way to the grocery store.",
        "I befriended a sentient robot that needed my help.",
        "A sentient plant convinced me to start a revolution.",
        "A rogue spell caused my house to turn invisible.",
        "I had to escape from a labyrinth of my own making.",
        "A talking crow sent me on a treasure hunt.",
        "A runaway carousel horse carried me to the countryside."
    ]
};

function generateExcuse(category) {
    const excuseArea = document.getElementById('excuse');
    if (excuses[category]) {
        const randomExcuse = excuses[category][Math.floor(Math.random() * excuses[category].length)];
        excuseArea.textContent = randomExcuse;
    } else {
        excuseArea.textContent = "Select a valid category!";
    }
    const favicon = document.getElementById('favicon');
favicon.href = `icons/${category}.png`;
};

